apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: {{deployment_name}}
  name: {{deployment_name}}
  namespace: {{deployment_namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{deployment_name}}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: {{deployment_name}}
    spec:
      containers:
      - name: {{deployment_name}}
        image: {{deployment_image}}
        imagePullPolicy: Always
        env:
          - name: FOO
            value: BAR
        ports:
          - containerPort: {{container_port}}
            name: {{port_name}}
      serviceAccountName: {{deployment_name}}
      restartPolicy: Always
      securityContext:
        runAsUser: 101