apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{deployment_name}}
  namespace: {{deployment_namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{host_name}}
    secretName: {{deployment_name}}-tls
  rules:
  - host: "{{host_name}}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{deployment_name}}
          servicePort: {{service_port}}