apiVersion: v1
kind: Service
metadata:
  name: {{deployment_name}}
  namespace: {{deployment_namespace}}
  labels:
    component: {{deployment_name}}
spec:
  selector:
    component: {{deployment_name}}
  ports:
  - name: {{port_name}}
    port: {{service_port}}
    targetPort: {{port_name}}